WebUITamhmor/WebUITamhmor/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebUITamhmor.Controllers
{
    public class ChatController : Controller
    {
        public IActionResult Chat()
        {
            return View();
        }

        public IActionResult Chatroom()
        {
            return View();
        }
    }
}

WebUITamhmor/WebUITamhmor/Controllers/DetailDoctorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Dynamic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using WebUITamhmor.Models;

namespace WebUITamhmor.Controllers
{
    public class DetailDoctorController : Controller
    {
        string Baseurl = "https://localhost:44305";

        public async Task<ActionResult> DetailDoctor(int Did)
        {
           
            List<DoctorModel> DoctorInfo = new List<DoctorModel>();
            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync("/api/v1/Doctor/GetDoctor");

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var DoctorResponse = Res.Content.ReadAsStringAsync().Result;
                    Debug.WriteLine(DoctorResponse);
                    Debug.WriteLine("====================");

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    var tempDataList = JsonConvert.DeserializeObject<List<DoctorModel>>(DoctorResponse);
                    // check Dsex map value
                    //Debug.WriteLine(DoctorInfo);
                    //var test = tempDataList.Find(x => x.Did == Did);
                    //DoctorInfo.Clear();
                    DoctorInfo.Add(tempDataList.Find(x => x.Did == Did));
                }

                //var detailDoctor = context.Doctors.Where(x => x.Did == Did).ToList();
                //return View();
                return View(DoctorInfo);
            }
        }

        public async Task<ActionResult> ListDoctor(string Ddepartment)
        {

            List<DoctorModel> DoctorInfo = new List<DoctorModel>();
            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync("/api/v1/Doctor/GetDoctor");

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var DoctorResponse = Res.Content.ReadAsStringAsync().Result;
                    Debug.WriteLine(DoctorResponse);
                    Debug.WriteLine("====================");

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    var tempData = JsonConvert.DeserializeObject<List<DoctorModel>>(DoctorResponse);


                    // check Dsex map value
                    //Debug.WriteLine(DoctorInfo);

                    DoctorInfo = tempData.FindAll(x => x.Ddepartment == Ddepartment);

                }
                
                return View(DoctorInfo);
            }
        }

        public async Task<ActionResult> DepartmentDoctor()
        {
            

            List<DoctorModel> DoctorInfo = new List<DoctorModel>();
                using (var client = new HttpClient())
                {
                    //Passing service base url  
                    client.BaseAddress = new Uri(Baseurl);

                    client.DefaultRequestHeaders.Clear();
                    //Define request data format  
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                    HttpResponseMessage Res = await client.GetAsync("/api/v1/Doctor/DepartmentDoctor");

                    //Checking the response is successful or not which is sent using HttpClient  
                    if (Res.IsSuccessStatusCode)
                    {
                        //Storing the response details recieved from web api   
                        var DoctorResponse = Res.Content.ReadAsStringAsync().Result;
                        Debug.WriteLine(DoctorResponse);
                        Debug.WriteLine("====================");

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    DoctorInfo = JsonConvert.DeserializeObject<List<DoctorModel>>(DoctorResponse);
                    // check Dsex map value
                    Debug.WriteLine(DoctorInfo);

                    

                }

                    return View(DoctorInfo);
                }
        }

        
        
    }
}

WebUITamhmor/WebUITamhmor/Views/Chat/Chat.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-analytics.js"></script>




    <style>
        .body {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Chakra Petch', sans-serif;
            outline-style: none;
        }


        .box_input {
            width: 300px;
            height: 200px;
            margin: 250px auto;
            padding: 50px;
            text-align: center;
            line-height: 60px;
            border: 1px solid #c5c5c5;
            border-radius: 15px;
        }

            .box_input input {
                border-radius: 5px;
                border: none;
                width: 100%;
                height: 40px;
                padding-left: 10px;
                background-color: #eeeeee;
            }

            .box_input button {
                border: none;
                background-color: paleturquoise;
                width: 100%;
                height: 40px;
                border-radius: 5px;
            }

        .box_chat {
            background-color: rgb(238, 238, 238);
            width: 400px;
            height: 600px;
            margin: 50px auto;
            display: grid;
            grid-template-rows: 60px 1fr 60px;
        }

        .top {
            display: flex;
            align-items: center;
            padding-left: 5px;
            color: black;
            width: 100%;
            height: 60px;
            background-color: paleturquoise;
        }

        .input_box {
            width: 100%;
            height: 60px;
            display: flex;
            align-items: center;
            background-color: paleturquoise;
            padding: 10px;
        }

            .input_box input {
                border: none;
                height: 100%;
                width: 85%;
                padding-left: 10px;
            }

        .box_messages {
            width: 100%;
            height: 100%;
            padding: 20px;
            overflow-x: hidden;
            overflow-y: auto;
        }

        .input_box button {
            margin-left: 5px;
            height: 100%;
            width: 15%;
            border: none;
            background-color: #00a3cc;
            color: white;
            /*border-radius: 0 15px 15px 0;*/
        }

        .msg_me {
            background-color: aqua;
            width: auto;
            max-width: 70%;
            padding: 10px;
            border-radius: 15px 0 15px 15px;
        }

        .msg_user {
            background-color: rgb(196, 196, 196);
            width: auto;
            max-width: 70%;
            padding: 10px;
            border-radius: 0 15px 15px 15px;
        }
    </style>



</head>
<body>

    



    
    <div class="container">
        <div class="box_chat">
            <div class="top">
                <h2>CHAT ROOM</h2>
            </div>

            <div id="box_messages" class="box_messages">

            </div>
            <div class="input_box">
                <input id="msg_text" type="text" placeholder="พิมพ์ข้อความ...">
                <button onclick="send()">ส่ง</button>
            </div>
            <button> @Html.ActionLink("ออก", "DepartmentDoctor", "DetailDoctor")</button>
        </div>
    </div>

</body>
</html>

<script>
    var firebaseConfig = {
        apiKey: "AIzaSyDKcXzhG21zy5XIHJTinT9hddznAEGngdM",
        authDomain: "tamhomn.firebaseapp.com",
        databaseURL: "https://tamhomn-default-rtdb.firebaseio.com",
        projectId: "tamhomn",
        storageBucket: "tamhomn.appspot.com",
        messagingSenderId: "919411017243",
        appId: "1:919411017243:web:8477a079ed18dc5c15dabe",
        measurementId: "G-BP59ZFJVC9"
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();


    var name = localStorage.getItem("name");

    function send() {
        var msg = document.getElementById('msg_text').value;
        if (msg != "") {
            firebase.database().ref("messages").push({
                msg: msg,
                sender: name

            }).then(function () {
                document.getElementById('msg_text').value = "";
            })
            console.log(msg);
        }
    }

    firebase.database().ref("messages").on("child_added", function (snapshot) {
        var username = snapshot.val().sender;
        var msg = snapshot.val().msg;
        var html = "";

        if (username == name) {
            html += "<div class='message_me' align='right'><p class='user'>" + username + "</p><p class='msg_me'>" + msg + "</p></div>";
            document.getElementById("box_messages").innerHTML += html;

        } else {
            html += "<div class='message_user' align='left'><p class='user'>" + username + "</p><p class='msg_user'>" + msg + "</p></div>";
            document.getElementById("box_messages").innerHTML += html;
        }

        var div_obj = document.getElementById("box_messages");
        div_obj.scrollTop = div_obj.scrollHeight;
    });
</script>

WebUITamhmor/WebUITamhmor/Views/Chat/ChatRoom.cshtml
@model IEnumerable<WebUITamhmor.Models.DoctorModel>
@{
    ViewData["Title"] = "Chat";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @*<link href="C:\Users\User\Desktop\Projct tamhmor\Tamhmor1\WebUITamhmor\WebUITamhmor\Style.css" rel="stylesheet" />*@
        <link rel="stylesheet" type="text/css" href="C:\Users\User\Desktop\Projct tamhmor\Tamhmor1\WebUITamhmor\WebUITamhmor\Style.css">
    
    @*<link href="https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@500&display=swap" rel="stylesheet">*@
    <title>Main</title>
</head>
<body>
    <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-app.js"></script>

    <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-analytics.js"></script>


    <script src="C:\Users\User\Desktop\Projct tamhmor\Tamhmor1\WebUITamhmor\WebUITamhmor\Script.js"></script>

    <div class="container">
        <div class="box_input">
            <input type="text" placeholder="ชื่อผู้ใช้" id="input_name"><br>
            <button id="btn_login" onclick="login()" disabled>แชท</button>

        </div>
    </div>

</body>
</html>

WebUITamhmor/WebUITamhmor/Views/Chat/Chatroom.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<link href="C:\Users\admin\source\repos\WebUITamhmor\WebUITamhmor\Views\Chat\Style.css" rel="stylesheet" />*@
    <style>
        .body {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Chakra Petch', sans-serif;
            outline-style: none;
        }

        .box_input {
            width: 300px;
            height: 200px;
            margin: 250px auto;
            padding: 50px;
            text-align: center;
            line-height: 60px;
            border: 1px solid #c5c5c5;
            border-radius: 15px;
        }

            .box_input input {
                border-radius: 5px;
                border: none;
                width: 100%;
                height: 40px;
                padding-left: 10px;
                background-color: #eeeeee;
            }

            .box_input button {
                border: none;
                background-color: paleturquoise;
                width: 100%;
                height: 40px;
                border-radius: 5px;
            }

        .box_chat {
            background-color: rgb(238, 238, 238);
            width: 400px;
            height: 600px;
            margin: 50px auto;
            display: grid;
            grid-template-rows: 60px 1fr 60px;
        }

        .top {
            display: flex;
            align-items: center;
            padding-left: 5px;
            color: black;
            width: 100%;
            height: 60px;
            background-color: paleturquoise;
        }

        .input_box {
            width: 100%;
            height: 60px;
            display: flex;
            align-items: center;
            background-color: paleturquoise;
            padding: 10px;
        }

            .input_box input {
                border: none;
                height: 100%;
                width: 85%;
                padding-left: 10px;
            }

        .box_messages {
            width: 100%;
            height: 100%;
            padding: 20px;
            overflow-x: hidden;
            overflow-y: auto;
        }

        .input_box button {
            margin-left: 5px;
            height: 100%;
            width: 15%;
            border: none;
            background-color: #00a3cc;
            color: white;
            /*border-radius: 0 15px 15px 0;*/
        }

        .msg_me {
            background-color: aqua;
            width: auto;
            max-width: 70%;
            padding: 10px;
            border-radius: 15px 0 15px 15px;
        }

        .msg_user {
            background-color: rgb(196, 196, 196);
            width: auto;
            max-width: 70%;
            padding: 10px;
            border-radius: 0 15px 15px 15px;
        }




    </style>
</head>
<body>
    <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-analytics.js"></script>
    @*<script src="C:\Users\admin\source\repos\WebUITamhmor\WebUITamhmor\Views\Chat\Script.js"></script>*@

    <div class="container">
        <div class="box_input">
            <input type="text" placeholder="ชื่อผู้ใช้" id="input_name"><br>
            <button id="btn_login" onclick="login()" disabled>แชท</button>

        </div>
    </div>

</body>
</html>
<script>
    function login() {
        var name = document.getElementById("input_name").value;
        localStorage.setItem("name", name);
        window.location.replace("Chat");


    }

    setInterval(function () {
        var name = document.getElementById("input_name").value;
        if (name != "") {
            document.getElementById("btn_login").disabled = false;
        } else {
            document.getElementById("btn_login").disabled = true;
        }
    }, 100) 
</script>